FROM nginx:1.27.1-alpine
COPY ./thinking.png /usr/share/nginx/html/thinking.png
COPY ./cubes.png /usr/share/nginx/html/cubes.png
COPY ./sidecar.png /usr/share/nginx/html/sidecar.png
COPY ./index.html /usr/share/nginx/html/index.html
EXPOSE 80
