version: '3'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - backend
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8090:80"
    environment:
      - BACKEND_URL=http://localhost:3000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
