version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - redis
  
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  
  frontend:
    build: ./frontend
    ports:
      - "8090:8080"
    environment:
      - BACKEND_URL=http://localhost:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "3000:3000"

