services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "8000:80"
    networks:
      redis-sleight-of-hand:
        ipv4_address: 172.32.0.2

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      redis-sleight-of-hand:
        ipv4_address: 172.32.0.3

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    hostname: frontend
    ports:
      - "8090:80"
    environment:
      - BACKEND_URL=http://backend:3000
    networks:
      redis-sleight-of-hand:
        ipv4_address: 172.32.0.4

  backend:
    build:
      context: ./backend
    container_name: backend
    hostname: backend
    ports:
      - "3000:3000"
    networks:
      redis-sleight-of-hand:
        ipv4_address: 172.32.0.5

networks:
  redis-sleight-of-hand:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16
          gateway: 172.32.0.1